# Site settings
title: Cindy Juarez
email: sceendy@gmail.com
description: >
  Cindy Juarez (sceendy) is a front-end engineer based in Austin, Texas.
baseurl: ""
url: "http://sceendy.com"
twitter_username: sceendy
github_username:  sceendy
disqusid: 'sceendyblog'

# Build settings
markdown: kramdown
sass:
  style: compressed
